# March 2022

## New Py Scripts

### Notes added to the NST_notes.md file

- apps/toonify/src/NST_train_single_image.py >> Run this file to train NST on a new style and input pair. At least 2000 epochs are recommended.

- apps/toonify/src/stylization_script.py >> Run this file to transfer input image into pre-trained styles. There are 4 pre-trained models are available in models/binaries folder.

- apps/toonify/src/training_script.py >> To train NST on new style. This will save the pre-trained model which can be used to transfer images afterwards.

- apps/toonify/src/utils/ >> This utils folder consists of scripts for download pre-trained models from dropbox and other helper functions.

### Answer

I have a question about these files: NST_train_single_image.py, stylization_script.py and training_script.py

When I used the NST script, I just used a style image and an input image and called NST.py like this:
python apps/toonify/src/NST.py --input_dir input.jpg --style_image style.jpg --output_dir gen_img

(I guess you renamed NST.py to NST_train_single_image.py, right?)
Anyhow, your notes seem to indicate I need to train images on the style images first?
You're notes seem to suggest that there is a lot more involved:
Run this file to train NST on a new style and input pair. At least 2000 epochs are recommended.
Run this file to transfer input image into pre-trained styles. There are 4 pre-trained models are available in models/binaries folder.
To train NST on new style. This will save the pre-trained model which can be used to transfer images afterwards.

To train NST on new style. This will save the pretrained model which can be used to transfer images afterwards.

### NST_train_single_image.py

This one uses one of the pre-trained models so it's not training here. This is the main file to use.

### stylization_script.py

I have not trained with this one as it requires huge data and more time but just added here in case you want to train your own style. Once you train using this script it saves the pretrained models that you can later use in stylization_script.py

### training_script.py

You don't have to train unless you want a new style.

## Previous use of the NST script

The script was called like this:

python apps/toonify/src/NST.py

```py
parser.add_argument(
    '--input_dir', default='C:/Users/timof/repos/timofeysie/satisfactory/apps/toonify/src/test_img/Trump-Kim_Summit_June_2018_v4.jpg')
parser.add_argument(
    '--style_image', default='C:/Users/timof/repos/timofeysie/satisfactory/apps/toonify/src/style_img/Overlooking_Stampa_Augusto_Giacometti_(1908).jpg')
...
save_image(generated_image, "gen_" + opt.input_dir)
```

Here is the list of [commits](https://github.com/timofeysie/satisfactory/commits/develop) to figure out how to use the scripts.

### Scripts added

Scripts and commit messages:

```txt
NST_train_single_image.py - NST new pretrained models and training code
stylization_script.py - NST new pretrained models and training code
test.py - NST pretrained models and training code
test_image_cyclegan.py - Cyclegan pretrained models and test script
training_script.py - NST new pretrained models and training code
```

In test.py, paths were changed to relative paths:

parser.add_argument('--input_dir', default = './test_img/')

However, the generate images does not seem to be working anymore.

I have seen some strange images in the apps\toonify\src\cartooned_img directory.

Why are these files there?

Alex_De_Minaur_%2828938823637%29_sezanne.jpg
Alex_De_Minaur_%2843875330731%29_sezanne.jpg
Bundesarchiv_Bild_146-1991-014-09%2C_Stein-Pfalz%2C_Ritter_und_Justin_bei_Blutabnahme_sezanne.jpg

I think these must be the failed images El was talking about.  Was that using the Cezanne model.  Since his French name has an accent over the e: Paul CÃ©zanne, I'm guessing that's what that encoded character is: %29_sezanne

When I run the test.py script from the command line, I get this:

```txt
> python apps/toonify/src/test.py --style Hosoda --gpu 0
Traceback (most recent call last):
  File "C:\Users\timof\repos\timofeysie\satisfactory\apps\toonify\src\test.py", line 27, in <module>
    model.load_state_dict(torch.load(os.path.join(opt.model_path, opt.style + '_net_G_float.pth')), strict=False)
  File "C:\Users\timof\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 594, in load   
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\timof\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\timof\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './pretrained_model/Hosoda_net_G_float.pth'
PS C:\Users\timof\repos\timofeysie\satisfactory>
```

Change the new version:

parser.add_argument('--input_dir', default = './test_img/')

Back to the old version:

parser.add_argument('--input_dir', default='apps/toonify/src/test_img/')

And it works.

## What happened to the download images?

linkWrapper {
  links: 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Corporal_Ben_Roberts-Smith_VC_investiture_%285%29.jpg'
}

Error: ENOENT: no such file or directory, open 'C:\Users\timof\repos\satisfactory\apps\toonify\src\test_img\Corporal_Ben_Roberts-Smith_VC_investiture_%285%29.jpg'

What is this?

Version: typescript 4.2.4
Time: 426ms
Command failed: taskkill /pid 4868 /T /F
ERROR: The process "4868" not found.

Debugger listening on ws://localhost:60881/6b8b907e-b01e-439a-80bf-7b1d06e12e08
Debugger listening on ws://localhost:60882/6b8b907e-b01e-439a-80bf-7b1d06e12e08
For help, see: <https://nodejs.org/en/docs/inspector>
[Nest] 6312   - 05/03/2022, 11:14:49 pm   [NestFactory] Starting Nest application...
[Nest] 6312   - 05/03/2022, 11:14:49 pm   [InstanceLoader] HttpModule dependencies initialized +49ms
...

The linkWrapper {
  links: 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Corporal_Ben_Roberts-Smith_VC_investiture_%287%29.jpg'
}

### The steps for a download

libs\trends\src\lib\containers\trends\trends.component.ts

```ts
preFillForm() {
...
    // download images
    this.downloadImages();
```

### The actual result

```txt
id Milwaukee Bucks
ImagesService.fullUrl <https://commons.wikimedia.org/w/index.php?search=Milwaukee> Bucks&title=Special:MediaSearch&go=Go
list 40
linkWrapper {
  links: 'https://upload.wikimedia.org/wikipedia/commons/0/02/President_Joe_Biden_with_the_Milwaukee_Bucks_%2803%29.jpg'
}
gan.controller.downloadImage: name {
  path: 'https://upload.wikimedia.org/wikipedia/commons/0/02/',
  filename: 'President_Joe_Biden_with_the_Milwaukee_Bucks_%2803%29.jpg'
}
filestream created
gan.controller.downloadImage: axios ref response
[Nest] 8544   - 08/03/2022, 12:46:24 am   [ExceptionsHandler] ENOENT: no such file or directory, open 'C:\Users\timof\repos\satisfactory\apps\toonify\src\test_img\President_Joe_Biden_with_the_Milwaukee_Bucks_%2803%29.jpg' +349800ms
```

Did the download happen and the image just not save?

If we look at the response object, it seems to indicate yes:

gan.controller.downloadImage: axios ref response {
  status: 200,
  statusText: 'OK',
  headers: {
    date: 'Mon, 07 Mar 2022 05:15:42 GMT',

The error is in the reject block in the gan.controller.downloadImage() function which previously worked:

```ts
    return new Promise((resolve, reject) => {
      writer.on('finish', () => this.ganService.kickOffGan());
      writer.on('error', () => { reject }
```

So look at the path used.

C:\Users\timof\repos\satisfactory\apps\toonify\src\test_img\President_Joe_Biden_with_the_Milwaukee_Bucks_%2803%29.jpg' +349800ms

C:\Users\timof\repos\timofeysie\satisfactory-broken\apps\toonify\src\test_img

Right.  The repos position has change because the develop branch lost it's ref and the project was re-cloned and moved up a directory.  Where is there a hardwired path?

There were no directories:

- test_img
- gen_image
- cartooned_img

Someone needs to remember that these directories will have to be created if the project is moved again or cloned by someone else.  Why aren't they in the git repo?  They are not in the gitignore.  As far as is know, the app does not hard-wire the satisfactory directory anywhere

Error: ENOENT: no such file or directory, open 'C:\Users\timof\repos\satisfactory\apps\nest-demo\src\app\bart\summaries\https%3A%2F%2Fwww.fearthesword.com%2F2022%2F3%2F7%2F22964370%2Fevan-mobley-offensive-rebounding-breakdown.txt'

Maybe we need the apps\nest-demo\src\app\bart\summaries directory also?

The post is made, but there is no S3 bucket upload.  Here we go again:

writeBucketFile: File not found ./apps/nest-demo/src/app/gan/bucket/Zydrunas_Ilgauskas_Cleveland_Cavaliers_Hayao.jpg.json

Create that directory, but then we see this error:

bart.service.getArticleSummary: path ./apps/nest-demo/src/app/bart/summaries/https%3A%2F%2Fmeaww.com%2Frobert-kraft-dana-blumberg-engaged-tommy-hilfiger-engaged.txt
gan.service.upload: err [Error: ENOENT: no such file or directory, open 'C:\Users\timof\repos\satisfactory\apps\toonify\src\cartooned_img\Brian_Nord,_Becoming_Interplanetary_Paprika.jpg'] {

A simple solution would be to create the directory if it doesn't exist.  Does FS have such a function?  If not, here is the list of paths that do not exist when a repo is cloned:

## Directories needed

- ./apps/toonify/src/cartooned_img/test_img
- ./apps/toonify/src/cartooned_img/gen_image
- ./apps/toonify/src/cartooned_img/cartooned_img
- ./apps/nest-demo/src/app/bart/summaries
- ./apps/nest-demo/src/app/gan/bucket/
